---
title: "Boston General Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
boston_original_df <- read_csv("Data/zillow-boston.csv")
##view(boston_original_df)
boston_MA_df <- boston_original_df %>% filter(rstate == "MA")
boston_MA_df <- boston_MA_df %>% arrange(desc(price))
##view(boston_MA_df)
boston_MA_df
```
```{r}
boston_general <- boston_MA_df %>%
  mutate(avg_price = sum(price) / 38) %>%
  mutate(projected_rental_income = living_space * 4.50) %>%
  mutate(down_payment = price * .20) %>%
  mutate(principal = price - down_payment) %>%
  mutate(projected_mortgage_payment = ((principal/330) * 1.042)) %>%
  mutate(projected_mortgage_yr = projected_mortgage_payment * 12) %>%
  mutate(projected_rental_income_yr = (projected_rental_income * 12)) %>%
  mutate(ROI = (projected_rental_income_yr - projected_mortgage_yr) / projected_mortgage_yr)

boston_general
```
```{r}
boston_general_price <- boston_general %>%
  filter(property_type == "CONDO" |
           property_type == "SINGLE_FAMILY" |
           property_type == "MULTI_FAMILY" |
           property_type == "TOWNHOUSE") %>%
  group_by(property_type) %>%
  summarise(mean_price = mean(price)) %>%
  mutate(type = fct_reorder(property_type, mean_price))
boston_general_price
ggplot(data = boston_general_price, aes(x = property_type, y = mean_price)) + 
  geom_col() +
  coord_flip()

boston_general_price
```

```{r}
boston_general_price_2 <- boston_general %>%
  filter(property_type == "CONDO" |
           property_type == "SINGLE_FAMILY" |
           property_type == "MULTI_FAMILY" |
           property_type == "TOWNHOUSE") %>%
  group_by(property_type) %>%
  summarise(med_price = median(price)) %>%
  mutate(type = fct_reorder(property_type, med_price))
ggplot(data = boston_general_price, aes(x = property_type, y = mean_price)) +
  geom_boxplot() +
  coord_flip()
```



