---
title: "New York City Data Set"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
nyc <- read_csv("Data/nyc-rolling-sales.csv")
view(nyc)

nyc_properties <- nyc %>%
  mutate(property_type = fct_recode(`Building Class at Present`, C = "C2",
                                    C = "C7",
                                    C = "C4",
                                    C = "C6",
                                    C = "C0",
                                    C = "C5",
                                    C = "C3",
                                    C = "C1",
                                    D = "D5",
                                    D = "D9",
                                    D = "D7",
                                    D = "D4",
                                    D = "D0",
                                    D = "D6",
                                    D = "D1",
                                    D = "D3",
                                    R = "RR",
                                    R = "R2",
                                    R = "R4",
                                    R = "R1",
                                    R = "R8",
                                    R = "R9",
                                    R = "RK",
                                    R = "RS",
                                    R = "R5",
                                    R = "RB",
                                    R = "RG",
                                    R = "RT",
                                    R = "R3",
                                    S = "S3",
                                    S = "S4",
                                    S = "SS",
                                    S = "S2",
                                    S = "S9",
                                    S = "S5",
                                    S = "S1",
                                    K = "K4",
                                    K = "K1",
                                    K = "K2",
                                    K = "K9",
                                    K = "K6",
                                    M = "M9",
                                    M = "M3",
                                    M = "M1",
                                    M = "M4",
                                    A = "A9",
                                    A = "A4",
                                    A = "A5",
                                    B = "B3",
                                    B = "B1",
                                    B = "B9",
                                    O = "O2",
                                    O = "O3",
                                    O = "O1",
                                    O = "O5",
                                    O = "O6",
                                    O = "O4",
                                    L = "L9",
                                    L = "L8",
                                    L = "L1",
                                    L = "L3",
                                    H = "H1",
                                    H = "H8",
                                    H = "H3",
                                    H = "H2",
                                    G = "G6",
                                    G = "G2",
                                    G = "GW",
                                    G = "G9",
                                    P = "P7",
                                    P = "P9",
                                    N = "N2",
                                    V = "V1",
                                    V = "V2",
                                    I = "I7",
                                    I = "I9",
                                    Z = "Z9",
                                    Z = "Z3",
                                    U = "U6",
                                    E = "E1",
                                    J = "J5",
                                    N = "N9")) 

```
pokemon_legend <- pokemon_legend %>%
  mutate(Generation_cat2 = fct_recode(Generation_cat, Kanto = "1",
                                      Johto = "2", Hoenn = "3",
                                      Sinnoh = "4", Unova = "5",
                                      Kalos = "6"))

